/**
 * Stylelint config.
 *
 * Two rules here are the point of running it at all: the ac- BEM pattern and
 * the ban on `transition` inside components. Everything else is
 * stylelint-config-standard with a set of deliberate opt-outs, each of which is
 * a real decision rather than a preference — they are documented below so the
 * next person does not "fix" them.
 */
export default {
  extends: "stylelint-config-standard",

  rules: {
    /* --- The rules that actually enforce this design system --- */

    // .ac-block, .ac-block__element, .ac-block--modifier, .ac-col-2
    "selector-class-pattern": [
      "^ac-[a-z0-9]+(-[a-z0-9]+)*(__[a-zA-Z0-9]+)?(--[a-z0-9-]+)?$",
      {
        message:
          "Class names must be ac- prefixed BEM: .ac-block, .ac-block__element, .ac-block--modifier",
      },
    ],
    "keyframes-name-pattern": "^ac-[a-z0-9-]+$",
    "custom-property-pattern": "^(ac-)?[a-z0-9]+(-[a-z0-9]+)*$",

    // Law: state changes are instant redraws. A screen has no in-between frames.
    "declaration-property-value-disallowed-list": { "/^transition/": ["/.*/"] },

    // Law: one gas, one hue. Named colors would smuggle in a second one.
    "color-named": "never",

    /* --- Deliberate opt-outs --- */

    // The token files are copied byte-for-byte from the source design system;
    // rewriting rgba() to rgb( / ) or #000 to #000000 would break that promise.
    // rgba() also has broader support than the space-separated form.
    "color-function-notation": "legacy",
    "alpha-value-notation": "number",
    "color-hex-length": null,

    // Every -webkit- prefix here is load-bearing: backdrop-filter and
    // mask-image for Safari, appearance for older engines. Dropping them
    // degrades the plasma bloom on real browsers.
    "property-no-vendor-prefix": null,
    "value-no-vendor-prefix": null,

    // `@import "x.css"` is what the source used and what the bundler parses.
    "import-notation": "string",

    // Range syntax — (width <= 720px) — is unsupported before Safari 16.4.
    // This framework promises to work without a build step or a polyfill.
    "media-feature-range-notation": "prefix",

    // Generated by scripts/fetch-fonts.mjs; quoting every family is consistent.
    "font-family-name-quotes": null,

    /* --- Formatting noise, not correctness --- */
    "no-descending-specificity": null,
    "at-rule-empty-line-before": null,
    "custom-property-empty-line-before": null,
    "declaration-empty-line-before": null,
    "comment-empty-line-before": null,
    "rule-empty-line-before": null,
    "declaration-block-single-line-max-declarations": null,
  },

  overrides: [
    {
      /* The instant-redraw law is about UI state: a button does not ease into
         being pressed. It is not about the panel's physics. Plasma persistence
         IS a timed decay — that is the entire phenomenon — and the only way to
         hold an element on screen past `display: none` is a transition with
         allow-discrete. scripts/check-prohibitions.mjs already scopes its own
         `transition` ban to src/components/ for exactly this reason; this brings
         stylelint in line with it. Components stay instant. */
      files: ["src/tokens/effects.css", "src/base/a11y.css", "src/base/print.css"],
      rules: { "declaration-property-value-disallowed-list": null },
    },
  ],
};
